In [2]:
import numpy as np
import copy

In [98]:
action = ([1, 1, 1, 1, 1, 1, 1, 0, 0, 1])
P = np.array([0,1,39,39*44+38,38,70*13,37,345,352,39*44])
action
W = np.random.randint(0,80,39*45)
W_two = W.reshape((45, -1))

In [99]:
W_two

array([[57, 33, 26, ..., 27, 41,  0],
       [24,  2, 30, ..., 73, 14, 14],
       [ 4, 67, 69, ..., 23, 63, 52],
       ...,
       [49, 20, 26, ..., 10, 54, 57],
       [67, 70,  5, ..., 76, 60, 64],
       [71, 12, 79, ..., 49,  3, 68]])

In [100]:
taxi = 0
t = 0
for index,act in enumerate(action): #TODO
    if act:
        around= get_around2(P[index],W_two,4)
        around_load = sum(around.flatten()) #TODO
        if(around_load > 200):
            t = around_load - 200
            around_load = 200
            W[P[index]] = t
        print(around)
        

0 0
[[57 33 26 11 46]
 [24  2 30 49 57]
 [ 4 67 69 29 14]
 [ 0 75 57 63  4]
 [57 22 24 34 23]]
0 1
[[677   0   0   0   0  43]
 [  0   0   0   0   0  59]
 [  0   0   0   0   0  23]
 [  0   0   0   0   0  78]
 [  0   0   0   0   0  54]]
1 0
[[  0 734   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [ 65  39  22   1  14]]
44 38
[[13  2 62  7 33]
 [47 28  8 51  9]
 [24  4 10 54 57]
 [22 49 76 60 64]
 [50 37 49  3 68]]
0 38
[[39 41 27 41  0]
 [43 78 73 14 14]
 [ 1 55 23 63 52]
 [20 12  0 75  4]
 [32  4  6 15 61]]
23 13
[[43 23 15 60 30 48 70 30 65]
 [13 22 42 20 39 32 56 74 17]
 [15 53 65 66 76 10 18  8  5]
 [48 61 75 17  5 13  9 62 37]
 [61 55 74 58 58 18 61 32  8]
 [34 59 44 18 43 29 39 50 60]
 [54 58 10 55 57 73 54  5 50]
 [52 58 71 53 34 50 76 56  7]
 [76 34 48 23 43 63 53 22 31]]
0 37
[[ 51   0   0   0   0 593]
 [ 46   0   0   0   0   0]
 [ 61   0   0   0   0   0]
 [  5   0   0   0   0   0]
 [ 59   0   0   0   0   0]]
44 0
[[15 1

In [50]:
def get_around(index,W_two):
    x = int(index / 39)
    y = index % 39
    print(x,y)
    if y==0 and x == 0:
        around = copy.deepcopy(W_two[x:(x+2), y:(y+2)])
        W_two[x:(x+2), y:(y+2)] = 0
        return around
    elif y == 0:
        around = copy.deepcopy(W_two[(x-1):(x+2), y:(y+2)])
        W_two[(x-1):(x+2), y:(y+2)] =0
        return around
    elif x == 0:
        around = copy.deepcopy(W_two[x:(x+2), (y-1):(y+2)])
        W_two[x:(x+2), (y-1):(y+2)]= 0
        return around 
    around =  copy.deepcopy(W_two[(x-1):(x+2), (y-1):(y+2)])
    W_two[(x-1):(x+2), (y-1):(y+2)] = 0
    return around
    

In [61]:
action = ([1, 1, 1, 1, 1, 1, 1, 0, 0, 1])
P = np.array([0,1,39,39*44+38,38,70,37,345,352,39*44])
action
W = np.random.randint(0,80,39*45)
W_two = W.reshape((45, -1))
W_two

array([[28, 48, 67, ..., 35, 14, 45],
       [41, 73, 77, ..., 26, 75, 25],
       [28, 28, 38, ..., 63, 36, 69],
       ...,
       [11, 10, 66, ..., 61, 11, 51],
       [11, 30,  6, ..., 16, 13, 44],
       [56, 28, 36, ..., 27, 19,  9]])

In [83]:
W_two[43:46,0:2]

array([[11, 30],
       [56, 28]])

In [86]:
def get_around2(index,W_two,bound):
    x = int(index / 39)
    y = index % 39
    print(x,y)
    bound_left_x = x - bound if (x - bound > 0) else 0
    bound_left_y = y - bound if (y - bound > 0) else 0
    bound_right_x = x + bound + 1
    bound_right_y = y + bound + 1
    around =  copy.deepcopy(W_two[bound_left_x:bound_right_x, bound_left_y:bound_right_y])
    W_two[bound_left_x:bound_right_x, bound_left_y:bound_right_y]= 0
    return around
    