In [7]:
import torch
import numpy as np

In [41]:
q_value = torch.tensor([[1,2,3,5,5,6,7,8,9,10],[1,2,3,5,5,6,7,8,19,10]])
index = torch.tensor([[1,1,0,1,1,4,5,6,6,1,1]])
q_value
ndarray = q_value.numpy()
ndarray

array([[ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  5,  5,  6,  7,  8, 19, 10]], dtype=int64)

In [16]:
a_q_value = torch.gather(input=q_value, dim=1, index=index)
a_q_value

tensor([[2, 2, 1, 2, 2, 5, 6, 7, 7, 2, 2]])

array([[ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  5,  5,  6,  7,  8, 19, 10]], dtype=int64)

In [20]:
ndarray[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [53]:
for i in ndarray:
   for j,val in enumerate(i):
      print(j,val)

0 1
1 2
2 3
3 5
4 5
5 6
6 7
7 8
8 9
9 10
0 1
1 2
2 3
3 5
4 5
5 6
6 7
7 8
8 19
9 10


In [57]:

my_data = b'\x00\x00\x80?\x00\x00\x00@\x00\x00@@\x00\x00\x80@'
my_data


In [2]:
t = '01100011'
t

'01100011'

In [65]:
 data = np.fromstring(t, np.int32)

C:\Users\鲍宇滨\AppData\Local\Temp\ipykernel_4732\3795355809.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(t, np.int32)


In [66]:
a = t.encode(encoding=”utf-8”,errors=”strict”)

SyntaxError: invalid character in identifier (609567873.py, line 1)

In [29]:
list(t.rjust(10,'0'))

['0', '0', '0', '1', '1', '0', '0', '0', '1', '1']

In [32]:
np.array(list(t.rjust(10,'0')),dtype=np.int32)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [34]:
index = 0
ndarray = batch_a.numpy()
a_list = []
for i in ndarray:
    index = 0
    for idx, val in enumerate(i):
        index += val * 2 ** idx
    a_list.append(index)
a_list = torch.LongTensor(a_list).unsqueeze(1)

TypeError: 'int' object is not iterable